### ISSUE TITLE
Зайві файли

### ISSUE THREAD

**Issue by samaranin** [DmitryItyl/SnakeGameCPP#1]
Прибрати із репозиторію зайві файли та файли відлагодження
Залишити лише вихідний код, інструкції для запуску і використання.

**Comment by DmitryItyl** [comment]
Добрий день. Потрібні зміни внесено.

**Comment by DmitryItyl** [comment]
> Прибрати із репозиторію зайві файли та файли відлагодження Залишити лише вихідний код, інструкції для запуску і використання.

Добрий день. Потрібні зміни внесено
